# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fibonacci(x)
    if x === 1 || x === 2 || x === 0
        return x
    end

    return fibonacci(x - 1) + fibonacci(x - 2)
end

sum = 0
i = 1
while fibonacci(i) < 4000000
    if iseven(fibonacci(i))
        global sum += fibonacci(i)
    end
    global i += 1
end

println(sum)
